import Foundation

/// Pure capture decisions — no AppKit, no live pasteboard — so the privacy filter and the
/// kind-classification are unit-testable. The AppKit `ClipboardMonitor` reads the actual bytes.
enum ClipboardCapture {
    /// Standard markers password managers / transient tools set to opt out of clipboard managers.
    static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    /// True when the available types include a concealed/transient marker — never record these.
    static func isConcealed(types: [String]) -> Bool {
        types.contains { concealedTypes.contains($0) }
    }

    /// Whether a copy from `sourceBundleID` should be recorded given the exclusion list. An unknown
    /// source is recorded (we only skip apps the user explicitly excluded).
    static func shouldRecord(sourceBundleID: String?, excluded: Set<String>) -> Bool {
        guard let id = sourceBundleID else { return true }
        return !excluded.contains(id)
    }

    /// Classify the entry kind from the available pasteboard UTIs. Priority: file → image → color →
    /// rich text → url → plain text. Returns nil when nothing recordable is present.
    static func classify(types: [String]) -> ClipboardKind? {
        let set = Set(types)
        if set.contains(ClipboardUTI.fileURL) { return .file }
        if set.contains(ClipboardUTI.png) || set.contains(ClipboardUTI.tiff) { return .image }
        if set.contains(ClipboardUTI.color) { return .color }
        if set.contains(ClipboardUTI.rtf) { return .richText }
        if set.contains(ClipboardUTI.url) { return .url }
        if set.contains(ClipboardUTI.plainText) || set.contains("public.text") { return .text }
        return nil
    }
}
